-- OneWoW Addon File (GENERATED - do not edit manually)
-- OneWoW/Services/PredicateEngine/geartokens.lua
-- Generated by bin/wowhead/geartoken-ids.py
local _, ns = ...

ns.GearTokenIDs = {
    [102263]=true, [102264]=true, [102265]=true, [102266]=true, [102267]=true, [102268]=true, [102269]=true, [102270]=true, [102271]=true, [102272]=true,
    [102273]=true, [102274]=true, [102275]=true, [102276]=true, [102277]=true, [102278]=true, [102279]=true, [102280]=true, [102281]=true, [102282]=true,
    [102283]=true, [102284]=true, [102285]=true, [102286]=true, [102287]=true, [102288]=true, [102289]=true, [102290]=true, [102291]=true, [102318]=true,
    [102320]=true, [102321]=true, [102322]=true, [102323]=true, [104009]=true, [104010]=true, [104012]=true, [104013]=true, [104345]=true, [104347]=true,
    [114052]=true, [114053]=true, [114057]=true, [114058]=true, [114059]=true, [114060]=true, [114063]=true, [114066]=true, [114068]=true, [114069]=true,
    [114070]=true, [114071]=true, [114072]=true, [114073]=true, [114074]=true, [114075]=true, [114076]=true, [114077]=true, [114078]=true, [114079]=true,
    [114080]=true, [114082]=true, [114083]=true, [114084]=true, [114085]=true, [114086]=true, [114087]=true, [114088]=true, [114089]=true, [114090]=true,
    [114091]=true, [114092]=true, [114093]=true, [114094]=true, [114096]=true, [114097]=true, [114098]=true, [114099]=true, [114100]=true, [114101]=true,
    [114105]=true, [114108]=true, [114109]=true, [114110]=true, [114111]=true, [114112]=true, [119114]=true, [119115]=true, [119116]=true, [119117]=true,
    [119118]=true, [119119]=true, [119120]=true, [119121]=true, [119122]=true, [119123]=true, [119124]=true, [119125]=true, [122621]=true, [122622]=true,
    [122623]=true, [122624]=true, [122625]=true, [122626]=true, [122627]=true, [122628]=true, [122629]=true, [122630]=true, [122631]=true, [122632]=true,
    [122633]=true, [124550]=true, [124551]=true, [124552]=true, [124553]=true, [124554]=true, [124555]=true, [124556]=true, [124557]=true, [124558]=true,
    [124559]=true, [124560]=true, [124561]=true, [124562]=true, [127777]=true, [127778]=true, [127779]=true, [127780]=true, [127781]=true, [127782]=true,
    [127783]=true, [127784]=true, [127790]=true, [127791]=true, [127792]=true, [127793]=true, [127794]=true, [127795]=true, [127796]=true, [127797]=true,
    [127798]=true, [127799]=true, [127800]=true, [127803]=true, [127804]=true, [127805]=true, [127806]=true, [127807]=true, [127808]=true, [127809]=true,
    [127810]=true, [127816]=true, [127817]=true, [127818]=true, [127819]=true, [127820]=true, [127821]=true, [127822]=true, [127823]=true, [128348]=true,
    [147212]=true, [147213]=true, [147214]=true, [147215]=true, [147216]=true, [147217]=true, [147218]=true, [147219]=true, [147220]=true, [147221]=true,
    [147222]=true, [147223]=true, [152733]=true, [152735]=true, [152736]=true, [152740]=true, [152799]=true, [153173]=true, [153205]=true, [153206]=true,
    [153207]=true, [153208]=true, [153209]=true, [153210]=true, [153211]=true, [153212]=true, [153213]=true, [153214]=true, [153215]=true, [153216]=true,
    [167848]=true, [167850]=true, [167851]=true, [167853]=true, [167855]=true, [167858]=true, [187187]=true, [188162]=true, [188173]=true, [190741]=true,
    [194334]=true, [201362]=true, [206270]=true, [210595]=true, [217241]=true, [225948]=true, [229422]=true, [244354]=true, [259996]=true, [274272]=true,
}
